version: 2

project_name: hakoll

before:
  hooks:
    - go mod tidy

builds:
  - id: koll
    main: ./cmd/koll
    binary: koll
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: "checksums.txt"

changelog:
  use: git

