version: 2

project_name: kan

before:
  hooks:
    - go mod tidy

builds:
  - id: kan
    main: ./cmd/kan
    binary: kan
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: "checksums.txt"

changelog:
  use: git

